### ISSUE TITLE
Progress output to stderr

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#10]
PEAT produces no output when it is running so it is difficult to know if it is working or not, or how far it has progressed.

Can you add a `--verbose / -v` or `--quiet -q` option?

**Comment by tseemann** [comment]
@ralf0216 Any progress?

**Comment by RalfHsiao** [comment]
We update the new options: --verbose.
You can know that the number of reads have been trimmed.
Thank you for your advice.
