### ISSUE TITLE
Only uses 115% CPU even with -n 16

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#13]
I managed to find a FASTQ file that PEAT binary worked on.

However, no matter what I set `-n` to, it only ever seems to use about 115% CPU.

We have good disk i/o and 64 cores. my `$OMP_NUM_THREADS` is set to 8.

Any ideas?

**Comment by jhhung** [comment]
PEAT's splits the input chunk by chunk and run them in parallel.
If your fastq is small, it is possible that the parallelism is not going to at its optimal.
Would you might giving me the links to the fastq files you used?

**Comment by jhhung** [comment]
would you might go to the issue panel, I had some response to you.

Thanks for your interest in PEAT.

best,

Jui-Hung

**Comment by tseemann** [comment]
This happens on *all* FASTQ files I try.

For example this is R1 from a "PEAT paired" run:
```
Reads   3464931
Yield   346493100
GeeCee  31.7
MinLen  100
AvgLen  100
MaxLen  100
ModeLen 100
Phred   33
AvgQual 38.4
```
It takes about 30 seconds and sits at 116% CPU the whole time.

**Comment by tseemann** [comment]
Here are the files I tested from SRA:

```
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR192/002/SRR1922792/SRR1922792_1.fastq.gz
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR192/002/SRR1922792/SRR1922792_2.fastq.gz
```

Here is the command:

```
time PEAT paired -n 16 -o peat -1 SRR1922792_1.fastq -2 SRR1922792_2.fastq

real    0m36.891s
user    0m35.397s
sys     0m1.404s
```

Here is my "top" output:

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
105521 tseemann  20   0  477336 274248    740 S 110.3  0.1   0:13.53 PEAT
```

**Comment by RalfHsiao** [comment]
We have fixed the multi threading.
Thank you your advice.
