### ISSUE TITLE
Allow user to choose output R1 and R2 files (again)

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#18]
I have tried the new `--output_1` option you said you added in https://github.com/jhhung/PEAT/issues/5
However, it does not do what was requested.

If I do `--output_1 R1.trimmed.fq` I still get a file `R1.trimmed.fq_paired1.fq`. Why does it have the `_paired1.fq` on the end?

I can use `-o` if I want a prefix.

**Comment by RalfHsiao** [comment]
We fixed the problem and update the PEATv1.1 in release.
Thank you your advice.

**Comment by tseemann** [comment]
You still need to fix the --help ?

```
  --output_1 arg (=stdout)             Prefix for Output file part1 name,
                                       stdout by default
  --output_2 arg (=stdout)             Prefix for Output file part2 name,
                                       stdout by default
```
