### ISSUE TITLE
PEAT always uses 2 cpus even with -n 1

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#19]
It always seems to use 2 threads (200% CPU) ?
Do you have a main thread and a file reading thread ?
If I use -n 2 I get 300% CPU. I assume you use N+1 threads.

```
% PEAT paired -n 1 -1 R1.fq -2 R2.fq > /dev/null
```

```
% top
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 43455 tseemann  20   0  207196 143740    740 R 200.0  0.0   0:11.71 PEAT
```

**Comment by RalfHsiao** [comment]
We fix this problem and update the program in release.
Thank you your advice.
