### ISSUE TITLE
Core dump when given gzipped FASTQ files

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#2]
Using the supplied static binary for Linux:

```
% PEAT paired -1 R1.fq.gz -2 R2.fq.gz 
```

```PEAT: /media/ephemeral0/boost_1_55_0/boost/range/iterator_range_core.hpp:343: boost::iterator_range<IteratorT>::reference boost::iterator_range<IteratorT>::operator[](boost::iterator_range<IteratorT>::difference_type) const [with IteratorT = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; boost::iterator_range<IteratorT>::reference = char&; boost::iterator_range<IteratorT>::difference_type = long int]: Assertion`at >= 0 && at < size()' failed. **Aborted (core dumped)**

```
```

**Comment by jhhung** [comment]
Will be fixed after we evaluate issue #6

**Comment by tseemann** [comment]
Even if you never support GZIP files you should not core dump when you do get them.

**Comment by jhhung** [comment]
Right, we are working on it.

**Comment by RalfHsiao** [comment]
Now we support the GZIP files and update PEAT to v1.2 in release.
Thank you your advice.
