### ISSUE TITLE
peat_report.txt does not explain enough

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#23]
The new `peat_report.txt` is good but it does not explain enough.

Can you let us know _which_ adaptor sequences were common and trimmed?
Or k-mers?
Something so we can figure out what it was.

Maybe output the trimmed sequenced to `peat_discarded.fq` ?

**Comment by RalfHsiao** [comment]
We added the option --adapter_contexts in new release v.1.2.2 to output the adapter contexts.
Thank you for your advice.

**Comment by tseemann** [comment]
Can you please explain what the numbers "2" and "1" mean?
Are they for R1 and R2 reads?

```
The top numbers of adpater contexts:
Context Number
TTACGACCATGTCGTTCACA    2
TTTTG   1
TGAG    1
TG      1
TCTCTTTATTAGCCATTTGTTCTTGA      1
T       1
GGAACTTTCGAGGGG 1
GCTCCTAAGTCTC   1
GATCATTGCATGATCAGCCACGTGATCAGTGCATGATATCCACGTGATCAG     1
CTTCTCTTTATTAGTCATTTGCTTTTCAGG  1
```

Can you tell us how many reads matched each adapter context?

Does it make sense that `T` is an adaptor context?

**Comment by RalfHsiao** [comment]
The number "2” is the adapter number.
The number was aggregated by R1.
