### ISSUE TITLE
Report longest adapter sequences found

### ISSUE THREAD

**Issue by habibr** [jhhung/PEAT#27]
Your latest release can produce most frequent adapter sequences clipped-off from the reads. I have tried but the list was not so useful for me. The top-ten were mostly di- or tri-nucleotide long.

I think it is more useful if it can report most frequent adapters with minimal length of say 10 bp. Or better with user defined parameters.

**Comment by RalfHsiao** [comment]
We added the option --adapter_min_bp to assist in selecting the adapter in release v1.2.4.
Thank you for your advice.
