### ISSUE TITLE
--out_gzip causing segmentation faults

### ISSUE THREAD

**Issue by wwood** [jhhung/PEAT#28]
with `ln -s PEAT_linux_v1.2.4 peat`,
```
$ peat paired -1 ../fastq/ERR1103462_1.fastq.gz -2 ../fastq/ERR1103462_2.fastq.gz --output_1 ERR1103462_1.fastq.gz --output_2 ERR1103462_2.fastq.gz --out_gzip --adapter_min_bp 10 --adapter_contexts                                                                                                                                                               
gz decompress call
gz decompress call
Segmentation fault
```
This can be worked around using bash named pipes, like so (here using `pigz`, `gzip` would also work I presume).
```
$ peat paired -1 ../fastq/ERR1103462_1.fastq.gz -2 ../fastq/ERR1103462_2.fastq.gz --output_1 >(pigz >ERR1103462_1.fastq.gz) --output_2 >(pigz >ERR1103462_2.fastq.gz) --adapter_min_bp 10 --adapter_contexts
gz decompress call
gz decompress call
```

**Comment by karta9812137** [comment]
It was being fixed in the latest version.

Example: 
in test_file
$ ../bin/PEAT paired -1 test_paired1.fq -2 test_paired2.fq --out_gzip --output_1 AA --output_2 BB

Output: 
AA.gz  
BB.gz

**Comment by wwood** [comment]
Thanks. It seems though, that, at least in 16773bc5413ed792a7e081ec043a809551ec7ab0
* AA.gz and BB.gz are not gzip-compressed, they are plain fq.
```
uqbwoodc@curtin:20170630:/tmp/guix-build-peat-1.2.4-1.16773bc5.drv-0/peat-1.2.4-1.16773bc5-checkout$ bin/PEAT paired -1 test_file/test_paired1.fq.gz -2 test_file/test_paired2.fq.gz --output_1 /tmp/o1 --output_2 /tmp/o2
gz decompress call
gz decompress call
uqbwoodc@curtin:20170630:/tmp/guix-build-peat-1.2.4-1.16773bc5.drv-0/peat-1.2.4-1.16773bc5-checkout$ file /tmp/o2
/tmp/o2: ERROR: cannot open `/tmp/o2' (No such file or directory)
uqbwoodc@curtin:20170630:/tmp/guix-build-peat-1.2.4-1.16773bc5.drv-0/peat-1.2.4-1.16773bc5-checkout$ file /tmp/o2.gz 
/tmp/o2.gz: ASCII text
```
* with `-o` it segfaults
```
bin/PEAT paired -1 test_file/test_paired1.fq.gz -2 test_file/test_paired2.fq.gz -o /tmp/out --out_gzip
gz decompress call
gz decompress call
Segmentation fault
```
But, if I had to pick, I'd rather #32 be fixed :)

**Comment by karta9812137** [comment]
Hi~

You try this command

bin/PEAT paired -1 test_file/test_paired1.fq.gz -2
test_file/test_paired2.fq.gz --out_gzip --output_1 AA.gz --output_2 BB.gz

If you use "vim", it is like normal fastq.

But it size is small, you can "head" this file.

PEAT only output "-o" or "----out_gzip", it can not create directories.


Thanks to your feedback.
And other issues we will fix it.

If you have any question, welcome email to me.
ᐧ

2017-06-30 17:53 GMT+08:00 Ben J Woodcroft <notifications@github.com>:
