### ISSUE TITLE
--adapter_contexts seems to be a required option

### ISSUE THREAD

**Issue by wwood** [jhhung/PEAT#29]
```
$ peat paired -1 test_paired1.fq.gz -2 test_paired2.fq.gz >/dev/null
[Error]: adapter_min_bp is required the option: adapter_contexts
Aborted
```
```
$ peat paired -1 test_paired1.fq.gz -2 test_paired2.fq.gz --adapter_min_bp 10 >/dev/null
[Error]: adapter_min_bp is required the option: adapter_contexts
Aborted
```
```
$ peat paired -1 test_paired1.fq.gz -2 test_paired2.fq.gz --adapter_contexts >/dev/null
```
the last command works. As you can see specifying `adapter_min_bp` as suggested by the error msg does not help.

**Comment by jhhung** [comment]
should have been fixed in the latest version.

**Comment by wwood** [comment]
hmm, which version is this fixed in? I'm still seeing this error on current master https://github.com/jhhung/PEAT/commit/c2f94a2e17b7ee46d7a501f44903a498883bb5d3.

ta

**Comment by karta9812137** [comment]
I forgot push, now should have been fixed in the latest version.
