### ISSUE TITLE
Please make a new release (so many bugs fixed)

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#35]
Needed for brew and conda packaging

https://github.com/jhhung/PEAT/compare/v1.2.4...master

**Comment by tseemann** [comment]
Please?

**Comment by PhoebeWangintw** [comment]
@tseemann Sure we're working on it. We'll release it as soon as possible. Thanks for your support and patience!

**Comment by tseemann** [comment]
`Last release: 26 Feb 2016` - we've been waiting 3.5 years 🙂

**Comment by tseemann** [comment]
I can compile it now with the 1.2.5 release. Thank you. Filed 2 bugs.
