### ISSUE TITLE
Support gzip input and output files

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#6]
Gzip compressed FASTQ files are standard everywhere.

It might be easy to support via Heng Li's KSEQ C module: http://lh3lh3.users.sourceforge.net/parsefastq.shtml

**Comment by jhhung** [comment]
Will think about it.

**Comment by tseemann** [comment]
@jhhung  Can you simply just use the BOOST functions?

http://www.boost.org/doc/libs/1_43_0/libs/iostreams/doc/classes/gzip.html

**Comment by RalfHsiao** [comment]
We add this feature and update PEAT to 1.2 in release.
Thank you your advice.
