### ISSUE TITLE
Need a summary report of what was trimmed

### ISSUE THREAD

**Issue by tseemann** [jhhung/PEAT#7]
it would be useful to have a summary report explaining what was clipped.

```
% PEAT paired -o peat ....

% ls
peat_paired1.fq 
peat_paired2.fq 
peat_report.txt 
```

Which contains things like:
- number of pairs adaptors were found in
- total number of reads
- average length trimmed
- average input / output length
- what the common adaptors were

**Comment by tseemann** [comment]
@ralf0216 Do you need any assistance with this?

**Comment by RalfHsiao** [comment]
We add the new feature: After the trimmer program is over, the summary file_report.txt is generated.
Thank for your advice.

**Comment by tseemann** [comment]
It would be good to know the average length of the INPUT reads too, so we know how much was trimmed.
